name: Build Game Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: python build_simple.py windows
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: Order_of_the_Stone-Windows
        path: releases/windows/Order_of_the_Stone.exe
        retention-days: 90
  
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Mac executable
      run: python build_simple.py mac
    
    - name: Upload Mac executable
      uses: actions/upload-artifact@v3
      with:
        name: Order_of_the_Stone-Mac
        path: releases/mac/Order_of_the_Stone
        retention-days: 90

